### ISSUE TITLE
link inside a p tag and style applied is not correct

### ISSUE THREAD

**Issue by fabianlevin88** [Danitoloxx/webserver#6]
The <a> tag is nested inside a paragraph so when the user hovers over the link, the style applied to it is also the one defined for the paragraph. See the attached screenshot for reference.

**Steps to Reproduce**
1. Open the [page](https://danitolozaweb.herokuapp.com/practica).
2. Scroll down to the last text (before the "back to the top" button).
3. Hover over the link ("Clickeame esta").

**Expected Result**
The style applied should be the one defined for the anchor tag only.

**Actual Result**
Both the style for anchor and paragraph styles are applied.

<img width="1275" alt="Screen Shot 2019-08-16 at 18 50 26" src="https://user-images.githubusercontent.com/5333964/63200404-82c2c100-c057-11e9-95b3-b7b27e990d9d.png">

**Comment by Danitoloxx** [comment]
Modified the style error, removed the background in the paragraphs so as not to have any conflict with the link, I looked for a way to try to separate the effects both in the paragraph and in the link and I did not have good results.

New PR added.
